DASHBOARDSRC /opt/dashboard_sdk/2.4.0/lib/libaggnet.so DEST lib/libaggnet.so
TOMESRC /opt/tome/3.0.0_build19/bin/mwerrhandler DEST bin/mwerrhandler
TOMESRC /opt/tome/3.0.0_build19/lib/libtome.so DEST lib/libtome.so
TOMESRC /opt/tome/3.0.0_build19/lib/libtome_as.so DEST lib/libtome_as.so 
TOMESRC /opt/tome/3.0.0_build19/lib/libtomecppas.so DEST lib/libtomecppas.so
TOMESRC /opt/tome/3.0.0_build19/lib/libtome_tcl.so DEST lib/libtome_tcl.so
TOMESRC /opt/tome/3.0.0_build19/lib/libjtome.so DEST lib/libjtome.so
TOMESRC /opt/tome/3.0.0_build19/lib/libtomecpp.so DEST lib/libtomecpp.so
TOMESRC /opt/tome/3.0.0_build19/lib/libtome_ev.so DEST lib/libtome_ev.so
TOMESRC /opt/tome/3.0.0_build19/lib/libtome_mon.so DEST lib/libtome_mon.so